# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
r = Restaurant.create(name: "St James's Hotel", lng: -0.14028, lat: 51.506159, price: 40, food_style: "cuisine", description: "In Seven Park Place William Drabble has created his own inimitable style menu, influenced by classic French cuisine but made using the best British ingredients and taking inspiration from the seasons.  Of course, like any great chef, William has his signature dishes, poached native lobster tail with cauliflower purée and lobster butter sauce springs to mind, but his continuing love of good food ensures that each dish he creates is as exquisite as the next.", user_id: 1, city: "London"),
r1 = Restaurant.create(name: "Criterion Restaurant", lng: -0.134091, lat: 51.509704, price: 40, food_style: "cuisine", description: "The Criterion, situated in the heart of Piccadilly Circus, is an elegant and breathtakingly beautiful restaurant. Originally opened in 1874, the Grade II listed lavish space has undergone a gentle and sympathetic restoration of its spectacular interiors, adding warmth and softness to the space.", user_id: 1, city: "London"),
r2 = Restaurant.create(name: "Veeraswamy Restaurant", lng: -0.157228, lat: 51.515058, price: 40, food_style: "cuisine", description: "We’re closed for refurbishment until mid/end October, but our Pop-Up Pizzeria is open from 9 to 28 September. Click to find out more.", user_id: 1, city: "London"),
r3 = Restaurant.create(name: "Locanda Locatelli", lng: -0.138002, lat: 51.509897, price: 30, food_style: "cuisine", description: "IN KEEPING WITH VEERASWAMY’S UNUSUAL OPENING IN 1926, WE CONTINUE TO OFFER CLASSICAL CUISINE FROM SEVERAL REGIONS OF INDIA, WITH A PARTICULAR UNDERSTANDING OF THE FOOD THAT IS PREPARED IN PALACES AND GOURMET HOMES, ALONG WITH A SELECTION OF THE BEST OF ‘STREET FOOD’.", user_id: 1, city: "London"),
r4 = Restaurant.create(name: "The Waldorf Hilton Hotel London", lng: -0.118901, lat: 51.512561, price: 50, food_style: "cuisine", description: "At Hilton, dining options are designed with you in mind. Start the day with a hearty breakfast or nutritious light bite; savor innovative dishes prepared with only the freshest ingredients, or simply relax with a cup of coffee in the hotel lounge. From business brunches to pre-dinner drinks and everything in between, the options at Hilton are catered especially for you. ", user_id: 1, city: "London"),
r5 = Restaurant.create(name: "The Swan Shakespeare's Globe", lng: -0.096468, lat: 51.508238, price: 50, food_style: "cuisine", description: "We’re delighted to announce that the Balcony Room has undergone a refurbishment; with beautiful stripped back wooden floors and a fresh coat of paint. Our clean new look frames our stunning view, which can be enjoyed to the full by pulling back the French windows and stepping out onto the private balcony. ", user_id: 1, city: "London"),
r6 = Restaurant.create(name: "Boisdale of Canary Wharf", lng: -0.021658, lat: 51.505153, price: 30, food_style: "cuisine", description: "A lively restaurant serving traditional Scottish cuisine, with live music, whisky bar, cigar terrace, caviar and oyster bar and cigar library, overlooking the Thames and city skyline.", user_id: 1, city: "London"),
r7 = Restaurant.create(name: "Royal Court Bar", lng: -0.156492, lat: 51.49263, price: 30, food_style: "cuisine", description: "The Royal Court Box Office, Bookshop and Bar and Kitchen will be closed from 9 August until early September for refurbishment. Tickets are still available on our website and 020 7565 5000 – please call for more information", user_id: 1, city: "London"),
r8 = Restaurant.create(name: "Simpson's-in-the-Strand", lng: -0.1205, lat: 51.51057, price: 60, food_style: "cuisine", description: "For a true taste of all that is best in British cuisine there is no finer dining establishment than Simpson's-in-the-Strand. Only the finest seasonal ingredients are used by Master Cook Gerry Rae in a Bill of Fare that offers a wide range of classical dishes, including the best Roast Beef and Lamb in the country, and game in season. Roasts are carved at guests’ tables, from antique silver-domed trolleys, by Simpson's Master Carvers in a perfect example of restaurant theatre. Simpson's also serves the Great British Breakfast on weekdays, with the 'Ten Deadly Sins' for trencherman appetites.", user_id: 1, city: "London")