# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
r = Restaurant.create(name: "St James's Hotel", lng: -0.14028, lat: 51.506159, price: 40, food_style: "cuisine", description: "In Seven Park Place William Drabble has created his own inimitable style menu, influenced by classic French cuisine but made using the best British ingredients and taking inspiration from the seasons.  Of course, like any great chef, William has his signature dishes, poached native lobster tail with cauliflower purée and lobster butter sauce springs to mind, but his continuing love of good food ensures that each dish he creates is as exquisite as the next.", user_id: 1, city: "London"),
r1 = Restaurant.create(name: "Criterion Restaurant", lng: -0.134091, lat: 51.509704, price: 40, food_style: "cuisine", description: "The Criterion, situated in the heart of Piccadilly Circus, is an elegant and breathtakingly beautiful restaurant. Originally opened in 1874, the Grade II listed lavish space has undergone a gentle and sympathetic restoration of its spectacular interiors, adding warmth and softness to the space.", user_id: 1, city: "London"),
r2 = Restaurant.create(name: "Veeraswamy Restaurant", lng: -0.157228, lat: 51.515058, price: 40, food_style: "cuisine", description: "We’re closed for refurbishment until mid/end October, but our Pop-Up Pizzeria is open from 9 to 28 September. Click to find out more.", user_id: 1, city: "London"),
r3 = Restaurant.create(name: "Locanda Locatelli", lng: -0.138002, lat: 51.509897, price: 30, food_style: "cuisine", description: "IN KEEPING WITH VEERASWAMY’S UNUSUAL OPENING IN 1926, WE CONTINUE TO OFFER CLASSICAL CUISINE FROM SEVERAL REGIONS OF INDIA, WITH A PARTICULAR UNDERSTANDING OF THE FOOD THAT IS PREPARED IN PALACES AND GOURMET HOMES, ALONG WITH A SELECTION OF THE BEST OF ‘STREET FOOD’.", user_id: 1, city: "London"),
r4 = Restaurant.create(name: "The Waldorf Hilton Hotel London", lng: -0.118901, lat: 51.512561, price: 50, food_style: "cuisine", description: "At Hilton, dining options are designed with you in mind. Start the day with a hearty breakfast or nutritious light bite; savor innovative dishes prepared with only the freshest ingredients, or simply relax with a cup of coffee in the hotel lounge. From business brunches to pre-dinner drinks and everything in between, the options at Hilton are catered especially for you. ", user_id: 1, city: "London"),
r5 = Restaurant.create(name: "The Swan Shakespeare's Globe", lng: -0.096468, lat: 51.508238, price: 50, food_style: "cuisine", description: "We’re delighted to announce that the Balcony Room has undergone a refurbishment; with beautiful stripped back wooden floors and a fresh coat of paint. Our clean new look frames our stunning view, which can be enjoyed to the full by pulling back the French windows and stepping out onto the private balcony. ", user_id: 1, city: "London"),
r6 = Restaurant.create(name: "Boisdale of Canary Wharf", lng: -0.021658, lat: 51.505153, price: 30, food_style: "cuisine", description: "A lively restaurant serving traditional Scottish cuisine, with live music, whisky bar, cigar terrace, caviar and oyster bar and cigar library, overlooking the Thames and city skyline.", user_id: 1, city: "London"),
r7 = Restaurant.create(name: "Royal Court Bar", lng: -0.156492, lat: 51.49263, price: 30, food_style: "cuisine", description: "The Royal Court Box Office, Bookshop and Bar and Kitchen will be closed from 9 August until early September for refurbishment. Tickets are still available on our website and 020 7565 5000 – please call for more information", user_id: 1, city: "London"),
r8 = Restaurant.create(name: "Simpson's-in-the-Strand", lng: -0.1205, lat: 51.51057, price: 60, food_style: "cuisine", description: "For a true taste of all that is best in British cuisine there is no finer dining establishment than Simpson's-in-the-Strand. Only the finest seasonal ingredients are used by Master Cook Gerry Rae in a Bill of Fare that offers a wide range of classical dishes, including the best Roast Beef and Lamb in the country, and game in season. Roasts are carved at guests’ tables, from antique silver-domed trolleys, by Simpson's Master Carvers in a perfect example of restaurant theatre. Simpson's also serves the Great British Breakfast on weekdays, with the 'Ten Deadly Sins' for trencherman appetites.", user_id: 1, city: "London"),
r9 = Restaurant.create(name: "Rafayel on the Left Bank", lng: -0.177665, lat: 51.470257, price: 60, food_style: "Meat", description: "Rafayel on the Left Bank provides the perfect setting for any occasion, be it a conference, business meeting, product launch or social event. Our professional team of event managers will take care of every detail, ensuring that your event will be one to remember.", user_id: 1, city: "London"),
r10 = Restaurant.create(name: "The Ivy", lng: -0.128175, lat: 51.512818, price: 90, food_style: "Haute", description: "The Ivy is situated in the heart of London's West End, close to Leicester Square, Shaftsbury Avenue and the vibrant quarters of Covent Garden and Soho.  Open late each night, the restaurant is also perfect for post theatre dinner. The Royal Opera House, Coliseum and all other theatres are a short walk away.", user_id: 1, city: "London"),
r11 = Restaurant.create(name: "The River Café", lng: -0.224389, lat: 51.48418, price: 40, food_style: "Italian", description: "The River Café menu changes twice daily.", user_id: 1, city: "London"),
r12 = Restaurant.create(name: "Rules", lng: -0.123211, lat: 51.510743, price: 60, food_style: "cuisine", description: "Rules was established by Thomas Rule in 1798 making it the oldest restaurant in London. It serves traditional British food, specialising in classic game cookery, oysters, pies and puddings", user_id: 1, city: "London"),
r13 = Restaurant.create(name: "Grange Holborn Hotel", lng: -0.12176, lat: 51.519982, price: 50, food_style: "Hotel", description: "Our Bars and Restaurants in London have an eclectic mix of cuisines, from the award-winning Benihana Japanese Sushi and Hibachi Grill and healthy Tapas at Tower Bar and Grill to the more traditional à la carte dining menus of our boutique hotels.", user_id: 1, city: "London"),
r14 = Restaurant.create(name: "Hilton London Metropole Hotel", lng: -0.16959, lat: 51.519378, price: 50, food_style: "cuisine", description: "225 EDGWARE ROAD, LONDON, W2 1JU, UNITED KINGDOM", user_id: 1, city: "London"),
r6 = Restaurant.create(name: "Skylon", lng: -0.116651, lat: 51.50572, price: 70, food_style: "cuisine", description: "A BEAUTIFUL RESTAURANT, STYLISH GRILL AND DESTINATION BAR", user_id: 1, city: "London"),
r7 = Restaurant.create(name: "The Restaurant at St Paul's Cathedral", lng: -0.098301, lat: 51.513677, price: 40, food_style: "cuisine", description: "St Paul’s welcomes you to British food at its best. The menus in both the café and the restaurant have been carefully created using the finest British produce – featuring imaginative, beautifully prepared seasonal dishes to suit every palate, plus an outstanding range of fine wines. So whether you’re looking for an excellent fixed price lunch, traditional afternoon tea or just want to relax over coffee and homemade cakes you'll find fabulous food, attentive service and great value for money in the stunning surroundings of St Paul's Cathedral.", user_id: 1, city: "London"),
r8 = Restaurant.create(name: "The Wolseley", lng: -0.140589, lat: 51.507301, price: 60, food_style: "European", description: "The Wolseley is a café-restaurant in the grand European tradition located on Piccadilly, London, UK.", user_id: 1, city: "London")